### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Niha",
  "email": "niha@test.com",
  "password": "password123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "niha@test.com",
  "password": "password123"
}